### ISSUE TITLE
bug: issues pulling model (CORS)

### ISSUE THREAD

**Issue by tmattoneill** [jakobhoeg/nextjs-ollama-llm-ui#8]
I'm running the ollama server on localhost:11434. I go to "Settings" and try to pull a model as no models are listed in the dropdown (even though tinydolphin is pulled and working on localhost). However, the app pukes on this as follows:
`
 ⨯ TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async globalThis.fetch (/home/ubuntu/nextjs-ollama-llm-ui/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:57569)
    at async POST (webpack-internal:///(rsc)/./src/app/api/model/route.ts:7:22)
    at async /home/ubuntu/nextjs-ollama-llm-ui/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:63809
    at async eU.execute (/home/ubuntu/nextjs-ollama-llm-ui/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:53964)
    at async eU.handle (/home/ubuntu/nextjs-ollama-llm-ui/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:65062)
    at async doRender (/home/ubuntu/nextjs-ollama-llm-ui/node_modules/next/dist/server/base-server.js:1333:42)
    at async cacheEntry.responseCache.get.routeKind (/home/ubuntu/nextjs-ollama-llm-ui/node_modules/next/dist/server/base-server.js:1555:28)
    at async DevServer.renderToResponseWithComponentsImpl (/home/ubuntu/nextjs-ollama-llm-ui/node_modules/next/dist/server/base-server.js:1463:28)
    at async DevServer.renderPageComponent (/home/ubuntu/nextjs-ollama-llm-ui/node_modules/next/dist/server/base-server.js:1856:24)
    at async DevServer.renderToResponseImpl (/home/ubuntu/nextjs-ollama-llm-ui/node_modules/next/dist/server/base-server.js:1894:32)
    at async DevServer.pipeImpl (/home/ubuntu/nextjs-ollama-llm-ui/node_modules/next/dist/server/base-server.js:911:25)
    at async NextNodeServer.handleCatchallRenderRequest (/home/ubuntu/nextjs-ollama-llm-ui/node_modules/next/dist/server/next-server.js:271:17)
    at async DevServer.handleRequestImpl (/home/ubuntu/nextjs-ollama-llm-ui/node_modules/next/dist/server/base-server.js:807:17)
    at async /home/ubuntu/nextjs-ollama-llm-ui/node_modules/next/dist/server/dev/next-dev-server.js:331:20
    at async Span.traceAsyncFn (/home/ubuntu/nextjs-ollama-llm-ui/node_modules/next/dist/trace/trace.js:151:20)
    at async DevServer.handleRequest (/home/ubuntu/nextjs-ollama-llm-ui/node_modules/next/dist/server/dev/next-dev-server.js:328:24)
    at async invokeRender (/home/ubuntu/nextjs-ollama-llm-ui/node_modules/next/dist/server/lib/router-server.js:163:21)
    at async handleRequest (/home/ubuntu/nextjs-ollama-llm-ui/node_modules/next/dist/server/lib/router-server.js:342:24)
    at async requestHandlerImpl (/home/ubuntu/nextjs-ollama-llm-ui/node_modules/next/dist/server/lib/router-server.js:366:13)
    at async Server.requestListener (/home/ubuntu/nextjs-ollama-llm-ui/node_modules/next/dist/server/lib/start-server.js:140:13) {
  cause: Error: connect ECONNREFUSED ::1:11434
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 11434
  }
}
`

<img width="1178" alt="Screenshot 2024-02-13 at 10 10 48" src="https://github.com/jakobhoeg/nextjs-ollama-llm-ui/assets/4083139/7fe77205-58d6-4820-977b-b4c41163c6ff">
<img width="927" alt="Screenshot 2024-02-13 at 10 00 10" src="https://github.com/jakobhoeg/nextjs-ollama-llm-ui/assets/4083139/25bd5882-19f3-45c2-a9c9-e990bb6e40b8">

**Comment by tmattoneill** [comment]
For some reason the dropdown isn't displaying any models, despite there being several available. Not sure where to address this.

https://capture.dropbox.com/WQgF9o90QWc8hYUw

**Comment by jakobhoeg** [comment]
I just installed ollama fresh on my ubuntu pc and did experience the same if i run ollama serve. 
However, running it as a background [service](https://github.com/ollama/ollama/blob/main/docs/linux.md#start-ollama), fixed all of the above issues. I have no clue why this happens.

Could you give that a try and report back?

**Comment by tmattoneill** [comment]
I've still not gotten this to work, running as a service or otherwise. I pull from the UI, it downloads the model to my machine (I can see it in `ollama list` but it never appears in the dropdown of the UI so I can't run.

**Comment by jakobhoeg** [comment]
> I've still not gotten this to work, running as a service or otherwise. I pull from the UI, it downloads the model to my machine (I can see it in `ollama list` but it never appears in the dropdown of the UI so I can't run.

If you inspect the browser and go under the tab, "Network", is there then an error in the fetch request to the /api/tags?

**Comment by tmattoneill** [comment]
<img width="1373" alt="Screenshot 2024-02-14 at 11 54 40" src="https://github.com/jakobhoeg/nextjs-ollama-llm-ui/assets/4083139/46ca4126-24ac-4b22-a2d6-50ffeac30a56">

Yes indeed. a fail / error there.

**Comment by jakobhoeg** [comment]
> <img alt="Screenshot 2024-02-14 at 11 54 40" width="1373" src="https://private-user-images.githubusercontent.com/4083139/304725612-46ca4126-24ac-4b22-a2d6-50ffeac30a56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MTY1NzIsIm5iZiI6MTcwNzkxNjI3MiwicGF0aCI6Ii80MDgzMTM5LzMwNDcyNTYxMi00NmNhNDEyNi0yNGFjLTRiMjItYTJkNi01MGZmZWFjMzBhNTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTRUMTMxMTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTU4ODY2MmM5ZjYxYjcxOTU4NTE1NzRkNGY3Zjc2MTRiZjM3MjViYTdiZjJlMWRmZTM0MTQwMmM0OTc1YzY5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4wYERXpDg1GR7Dhcb-f3Cw0VvK5BzA34Cxk4UgT0_zI">
> Yes indeed. a fail / error there.

Can you click on it and see if it logs any error. Maybe even in the console tab

**Comment by tmattoneill** [comment]
Here's a dump of network + console screenshots and logs.
<img width="1394" alt="Screenshot 2024-02-14 at 13 22 05" src="https://github.com/jakobhoeg/nextjs-ollama-llm-ui/assets/4083139/c358c660-92f9-4989-8c7d-93a45b3c6230">
<img width="1384" alt="Screenshot 2024-02-14 at 13 21 58" src="https://github.com/jakobhoeg/nextjs-ollama-llm-ui/assets/4083139/6337a387-22b5-4dcb-82c5-4d519e74a06e">
<img width="1383" alt="Screenshot 2024-02-14 at 13 20 48" src="https://github.com/jakobhoeg/nextjs-ollama-llm-ui/assets/4083139/39d33d40-9192-462d-a065-2c5411a19bc0">
<img width="1400" alt="Screenshot 2024-02-14 at 13 19 52" src="https://github.com/jakobhoeg/nextjs-ollama-llm-ui/assets/4083139/7018894a-4ce0-4f47-be70-2c8cf56cf8e8">
[console-logs-oneill.zip](https://github.com/jakobhoeg/nextjs-ollama-llm-ui/files/14279910/console-logs-oneill.zip)

**Comment by tmattoneill** [comment]
as you can see, the manifest pulls and stores just fine. It's an issue w/ the dropdown populating with the valid models that is the issue I think

**Comment by Sutsikii** [comment]
Same on a prod website, i can pull model, but can't see them

**Comment by jakobhoeg** [comment]
Very odd.
I've  tried both my Windows pc running Ollama in WSL2, my Ubuntu laptop and my Macbook. I'm able to both pull and see all the pulled models.



> Same on a prod website, i can pull model, but can't see them

But it works locally for you?
Also, are you able to pull and chat on the prod website?

**Comment by tmattoneill** [comment]
I am unable to use the UI in any environment. MacOS / remote Ubuntu / etc. I can run Ollama just fine. I can see my new manifests after the pull. Could you set a "default model" e.g. "ollama2" in the case no model is specified? I haven't been able to do a chat in any environment since I can't choose due to the dropdown issue.

**Comment by jakobhoeg** [comment]
I'd rather fix the issue than setting a default model.
However, you can do a quick fix to the issue by inspecting the page and setting the selectedModel manually under local storage:

![image](https://github.com/jakobhoeg/nextjs-ollama-llm-ui/assets/114422072/88c43c7b-68c4-44b2-9d60-72ca92f06cef)

**Comment by Sutsikii** [comment]
> > Same on a prod website, i can pull model, but can't see them
> 
> But it works locally for you? Also, are you able to pull and chat on the prod website?

It work locally, i can pull on prod, but can't see on the dropdown !

**Comment by tmattoneill** [comment]
I can confirm that when I run 
`npm run dev`
locally on my MacBook everything works as expected. I have yet to be able to run this:

- on a docker instance locally
- on a remote server
- on any other machine on my network

**Comment by jakobhoeg** [comment]
> I can confirm that when I run `npm run dev` locally on my MacBook everything works as expected. I have yet to be able to run this:
> 
> * on a docker instance locally
> * on a remote server
> * on any other machine on my network

Very odd.
Thank you for your feedback and sorry for the hassle.
I'll be looking into this asap.

**Comment by tmattoneill** [comment]
Hassle? Don't be silly. It's my pleasure. This will be SUPER powerful when I can separate the LLM processing and the UI. You should check out https://power.netmind.ai they let you spin up a 4090 2X GPU machine (200GB HDD) for **FREE** during their beta. 

So what I'm trying to do is:
- Run the next UI on my web server
- Offload the LLM processing to the Ollama API on NetMind 4090 GPUs

It'll then be SUPER fast. You should check them out and have a place. You can run a huge model ridiculously fast.

<img width="1142" alt="Screenshot 2024-02-15 at 08 11 08" src="https://github.com/jakobhoeg/nextjs-ollama-llm-ui/assets/4083139/dc60e132-0a2b-43b4-aed5-d6381fcabb12">

<img width="972" alt="Screenshot 2024-02-15 at 08 10 51" src="https://github.com/jakobhoeg/nextjs-ollama-llm-ui/assets/4083139/8c899f72-3f1e-4a56-a5ab-e1d0cd6472eb">

**Comment by Leo512bit** [comment]
Hate to barge in here but I also have the same issue on native Windows (Not on WSL2) built from source (because the binary is not compiled with AVX512 enabled 👿). I also have the same issue with https://github.com/ivanfioravanti/chatbot-ollama/ but when I run the binary chatbot-ollama found the model just fine, I suspect that this will be the case here too (but I haven't tested it).

**Comment by jakobhoeg** [comment]
> Hate to barge in here but I also have the same issue on native Windows (Not on WSL2) built from source (because the binary is not compiled with AVX512 enabled 👿). I also have the same issue with https://github.com/ivanfioravanti/chatbot-ollama/ but when I run the binary chatbot-ollama found the model just fine, I suspect that this will be the case here too (but I haven't tested it).

No worries at all. 
Thanks for the feedback and link to the issue.

I still haven't had the time to look into this yet, but I will as soon as i have the time. Thanks for the patience.

**Comment by Leo512bit** [comment]
> No worries at all. Thanks for the feedback and link to the issue.

Well, it managed to fix itself, not sure how.

**Comment by tailnet-h-usky-io** [comment]
@jakobhoeg Thanks for your work on this UI - don't let the haters get to you when it doesn't work for everyone everywhere all the time!

Anyway, I'm having the same issue - that is, images pull fine, but do not show up in the dropdown list.

Weirdly, my browser is not making requests for `/api/tags` at all, despite page reloads, nor are any requests failing at all!

<img width="2105" alt="image" src="https://github.com/jakobhoeg/nextjs-ollama-llm-ui/assets/157428625/e81a270f-07d6-44b6-a0c5-6ef3229a4dd2">

Could this be because I had to build my own Docker image with the backend address hard-coded? I did not see any instructions for creating a production build, and I'm not a Javascript / NodeJS programmer, so I just banged out this `Dockerfile` after checking out the code base, and hoped for the best:

``` 
FROM node:21

COPY . /home/node/app
WORKDIR /home/node/app

ENV NPM_CONFIG_LOGLEVEL info
ENV NEXT_PUBLIC_OLLAMA_URL="http://ollama.h.usky.io:11434"

RUN npm install
RUN npm install sharp
RUN npm run build

EXPOSE 3000
```
The Env Var `NEXT_PUBLIC_OLLAMA_URL` referenced in the `README` for dev use does not seem to work as a runtime override. 

Still, I overrode it anyway in my Kubernetes spec...
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-ui
  template:
    metadata:
      labels:
        app: ollama-ui
    spec:
      containers:
      - name: ollama-ui
        image: ghcr.io/tailnet-h-usky-io/ollama-ui:v0.0.1
        ports:
        - containerPort: 3000
        command: ["npm", "start"]
        env:
        - name: NEXT_PUBLIC_OLLAMA_URL
          value: "http://ollama.h.usky.io:11434"

---
apiVersion: v1
kind: Service
metadata:
  name: ollama-ui-service
spec:
  selector:
    app: ollama-ui
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
```



How is the list of available models generated? Does `ollama` have an API call for it?

I'm running this on a private (sub)network in microk8s with `ollama` and `[nextjs-ollama-llm-ui` in different pods. The connection from B to A on ollama's regular API port (`11434`) seems fine.

**Comment by tailnet-h-usky-io** [comment]
Correction - I _do_ see the blocked request to. `/api/tags` in Safari's JS console.
<img width="1068" alt="image" src="https://github.com/jakobhoeg/nextjs-ollama-llm-ui/assets/157428625/a0b3a622-f19b-4168-9035-141e30753817">


Look like it could be a [CORS][1] problem. I believe that if the URL scheme that serves the Web UI is not the same as the URL scheme of the API server, CORS headers are required on the API server, or the browser will block the requests.


It's possible that adding the Header:
`Access-Control-Allow-Origin: *` 
to the Ollama API server may fix the problem. 


[1]:https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by tmattoneill** [comment]
This is exactly	what I’m seeing.

**Comment by tailnet-h-usky-io** [comment]
Seems there's a currently-open [ollama PR][1] that adds not just CORS support, but the full OpenID Connect consent workflow.

[1]:https://github.com/ollama/ollama/pull/1357

**Comment by jakobhoeg** [comment]
> Correction - I _do_ see the blocked request to. `/api/tags` in Safari's JS console. <img alt="image" width="1068" src="https://private-user-images.githubusercontent.com/157428625/306494854-a0b3a622-f19b-4168-9035-141e30753817.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1OTk2NjMsIm5iZiI6MTcwODU5OTM2MywicGF0aCI6Ii8xNTc0Mjg2MjUvMzA2NDk0ODU0LWEwYjNhNjIyLWYxOWItNDE2OC05MDM1LTE0MWUzMDc1MzgxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMlQxMDU2MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjUyMDc1MjAyODQwZmZmOWFlNzNkMTA0ZjkxODZlMWNkMDQ3M2MxMWUxZGE3MjhhNWI3NjQyY2FiYjQ3MGM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zDhtBnfgNvhxDmug7oczb3SiVXwb8zcewM0R8UfzOUg">
> 
> Look like it could be a [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) problem. I believe that if the URL scheme that serves the Web UI is not the same as the URL scheme of the API server, CORS headers are required on the API server, or the browser will block the requests.
> 
> It's possible that adding the Header: `Access-Control-Allow-Origin: *` to the Ollama API server may fix the problem.

Thanks for the feedback.
I think with your setup the issue might indeed be related to CORS. By default `localhost` and  `0.0.0.0` should be allowed as origins. However, since you're facing issues, have you tried setting the `OLLAMA_ORIGINS` to your `http://ollama.h.usky.io:11434`? Check out the [docs](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-allow-additional-web-origins-to-access-ollama). Please report back to me if it fixed your issue.

**Comment by jakobhoeg** [comment]
> Seems there's a currently-open [ollama PR](https://github.com/ollama/ollama/pull/1357) that adds not just CORS support, but the full OpenID Connect consent workflow.

Thanks for mentioning this PR.
It's a shame that its 3 months old and still open though.

**Comment by tailnet-h-usky-io** [comment]
OK, I got it working. Here are some tips based on my setup that may help if yours is similar...

1. Since I was running the UI and Ollama on separate containers with separate addresses, the Ollama container must be configured to allow cross-origin requests from the UI, as noted above. It was pointed out to me yesterday that Ollama already [supports this][1]. Adding the `OLLAMA_ORIGINS` env var with the _full URL scheme_ (protocol + host, in my case `https://chat.h.usky.io`), to the Ollama container stopped the browser from blocking this request.
2. I was initially running HTTPs on the `nextjs-ollama-llm-ui` front end, but plain HTTP on the Ollama API backend, as if the frontend were proxying all traffic to the Ollama API via the NPM server _(the so-called "back channel")_.  But of course, the frontend is a JS app that's making **direct requests** to the API via the browser _(the so-called "front channel")_, so the browser will not do this over HTTP if the page was loaded over HTTPS, because the user must be able to assume that any data submitted by the page they've loaded via HTTPs will be submitted securely. The browser recognizes this so-called "mixed-mode" CORS request, and blocks it. (I had to try a couple of different browsers and check their various error messages to figure this one out, but it makes sense in retrospect.)


[1]:https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-allow-additional-web-origins-to-access-ollama

**Comment by tailnet-h-usky-io** [comment]
So, to summarize...

If you're having this problem, it's probably because this JS frontend cannot pull the list of models/tags from the Ollama API endpoint. You should be able to verify this by looking in the JS Console immediately upon loading the UI _(no need to add a nickname or pull a model)_.
<img width="1068" alt="image" src="https://github.com/jakobhoeg/nextjs-ollama-llm-ui/assets/157428625/a0b3a622-f19b-4168-9035-141e30753817">
^^ If you see the blocked request to `api/tags`, then this CORS-related issue is almost certainly your problem. The URL scheme (protocol + host + port) for the blocked request should be **different from** the URL scheme in the location bar of your browser – that's what makes the request "cross origin". Note that you can change the base location of the blocked request by setting `NEXT_PUBLIC_OLLAMA_URL` in the environment where you run `nextjs-ollama-llm-ui `.

If you're being blocked by CORS rules. Here's how to fix it:

1. Ensure that the protocol in your browser _(for the JS frontend)_ and the protocol of the blocked request _(for the API server, read from the JS Console)_  are **both** _either_ HTTPs _or_ plain HTTP. In other words, if you're using HTTPs for one, you must use it for both! 
2. Copy the URI scheme – the protocol + host + port (e.g. `http://olllama-ui.mydomain.org`, or `http://127.0.0.1:3000`) – from the URL in your browser and restart the Ollama API server with the env var `OLLAMA_ORIGINS` set to the scheme's value.

**Comment by jakobhoeg** [comment]
> So, to summarize...
> 
> 
> 
> If you're having this problem, it's probably because this JS frontend cannot pull the list of models/tags from the Ollama API endpoint. You should be able to verify this by looking in the JS Console immediately upon loading the UI _(no need to add a nickname or pull a model)_.
> 
> <img width="1068" alt="image" src="https://github.com/jakobhoeg/nextjs-ollama-llm-ui/assets/157428625/a0b3a622-f19b-4168-9035-141e30753817">
> 
> ^^ If you see the blocked request to `api/tags`, then this CORS-related issue is almost certainly your problem. The URL scheme (protocol + host + port) for the blocked request should be **different from** the URL scheme in the location bar of your browser – that's what makes the request "cross origin". Note that you can change the base location of the blocked request by setting `NEXT_PUBLIC_OLLAMA_URL` in the environment where you run `nextjs-ollama-llm-ui `.
> 
> 
> 
> If you're being blocked by CORS rules. Here's how to fix it:
> 
> 
> 
> 1. Ensure that the protocol in your browser _(for the JS frontend)_ and the protocol of the blocked request _(for the API server, read from the JS Console)_  are **both** _either_ HTTPs _or_ plain HTTP. In other words, if you're using HTTPs for one, you must use it for both! 
> 
> 2. Copy the URI scheme – the protocol + host + port (e.g. `http://olllama-ui.mydomain.org`, or `http://127.0.0.1:3000`) – from the URL in your browser and restart the Ollama API server with the env var `OLLAMA_ORIGINS` set to the scheme's value. You can use multiple values, separated by commas _(I have not tried `*`)_.
> 
> 

What a very comprehensive guide! I'm very glad you got it working 🙏
@tmattoneill can you try and follow this to see if you can get it working? I'll update the readme then

**Comment by jakobhoeg** [comment]
@tmattoneill hey, any progress here? There has also just been a pull request merged, which might fix the issue.

**Comment by tmattoneill** [comment]
Thanks! I haven’t had a chance to go back AND my service provider was down last week. I’m finishing another project atm and will check this out later this week.

THANKYOU

**Comment by aetente** [comment]
for me I managed to fix the pulling only when I changed env name `OLLAMA_URL` to `NEXT_PUBLIC_OLLAMA_URL`
like it is said here: https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#bundling-environment-variables-for-the-browser
and also maybe setting `OLLAMA_ORIGINS` env for ollama itself to `localhost` and `127.0.0.1`, but not sure if it actually changed anything

**Comment by jakobhoeg** [comment]
@tmattoneill 
Merged a PR that should address this issue. I also added the ability to deploy your own on Vercel.
Let me know how it works out.
